### ISSUE TITLE
Exception after updating to last version 1.2.1

### ISSUE THREAD

**Issue by tcastelli** [MiroHibler/meteor-preloader#18]
Hi there, I've just updated the package, and I got this exception on all browsers
```
Exception in callback of async function: Preloader.loadLibs@http://localhost:3000/packages/miro_preloader.js?07b361b1abe7bd3b9526e0031b650b48d81b0173:525:1
PreloadController<.waitOn@http://localhost:3000/packages/miro_preloader.js?07b361b1abe7bd3b9526e0031b650b48d81b0173:585:11
RouteController.prototype._runRoute/<@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:438:15
_.forEach@http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:7
RouteController.prototype._runRoute@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:437:3
Route.prototype.dispatch@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:844:10
Route/route@http://localhost:3000/packages/iron_router.js?a427868585af16bb88b7c9996b2449aebb8dbf51:710:5
boundNext@http://localhost:3000/packages/iron_middleware-stack.js?0e0f6983a838a6516556b08e62894f89720e2c44:424:16
Meteor.bindEnvironment/<@http://localhost:3000/packages
```

My route is defined like this (it was working correctly before the update)

```
Router.map(function() {
    this.route('home', {
        path: '/',
        template: 'home',
        layoutTemplate: 'HomeLayout',
        controller: 'PreloadController',
        waitOn: function () {
            return [mfPkg,subs.subscribe("fullProfile")];
        },   
        'preload': {
            'async':[Meteor.settings.public.lib.turf],
            'sync': [Meteor.settings.public.lib.modernizr,
                Meteor.settings.public.lib.leaflet,
                Meteor.settings.public.lib.esrileaflet],
            'onSync': function (filePath) {
                var file = filePath.replace(/\?.*$/, "").replace(/.*\//, "");
                switch (file) {
                    case 'modernizr.min.js':
                        try {
                            return !!Modernizr;
                        } catch (error) {
                            return false;
                        }
                        break;
                    case 'leaflet.js':
                        try {
                            return !!L;
                        } catch (error) {
                            return false;
                        }
                        break;
                    case 'esri-leaflet-basemaps.js':
                        try {
                            return !!L.esri;
                        } catch (error) {
                            return false;
                        }
                        break;
                    default:
                    {
                        return true;
                    }
                }
            }
        }
    });
});
```

**Comment by MiroHibler** [comment]
Have you tried to trace the code?

**Comment by tcastelli** [comment]
I don't know exactly why this is happening but i found a solution,
currently, what i was trying, it was just to disable the verbose so i did this
```
Router.configure({
    trackPageView: true,
    'preload': {
        /*
         | Parameters can be a string (file path) or an array of strings
         */
        // Added in v1.2.1 - this one works only in Router.Configure!
        'verbose': false,  // Show loading messages in console,

    }
});
```

And the rest of the things were specified in the route itself. (I got the error by doing so).
To make it work, it seems that there needs to be something for preloader to do ath the global level, but since i didnt want to add any libraries or anything on the global level,  i just added
```
        // CSS style(s) to load
        'styles' : '' // or []
```

and now it's working. Hope it helps to track down the issue

**Comment by MiroHibler** [comment]
Oh, ok, it's more clear now - let check that...

**Comment by DanielRHarris** [comment]
Having the same issue, and same solution as @tcastelli works.

**Comment by MiroHibler** [comment]
Fixed with v1.2.3.

Thanks guys! :)

**Comment by DanielRHarris** [comment]
Thanks for working on this despite it being an easy bug to get around! Just wanted to let you know that it still isn't working though...

```Exception in callback of async function: loadLibs@http://localhost:3000/packages/miro_preloader.js?2a67fd271ee1cbc71da690fec848598bedff2fbd:545:34
waitOn@http://localhost:3000/packages/miro_preloader.js?2a67fd271ee1cbc71da690fec848598bedff2fbd:605:29
http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:439:26
forEach@[native code]
forEach@http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:18
_runRoute@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:438:9
dispatch@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:854:27
route@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:711:19
boundNext@http://localhost:3000/packages/iron_middleware-stack.js?56e0c02a758f48c0a704ca978a8fb6d7bd9ebbab:424:35
http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:27
dispatch@http://localhost:3000/packages/iron_middleware-stack.js?56e0c02a758f48c0a704ca978a8fb6d7bd9ebbab:448:7
http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:391:21
_compute@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36
Computation@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:18
autorun@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:34
http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:389:17
nonreactive@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:13
dispatch@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:388:19
dispatch@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1698:22
onLocationChange@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1782:33
_compute@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36
Computation@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:18
autorun@http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:34
start@http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:1775:43
http://localhost:3000/packages/iron_router.js?7b16fe70bccff9182aca02afb2ccd7708ac57c64:978:21
withValue@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:955:21
http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:435:54
http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:27
onGlobalMessage@http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:372:23```

**Comment by MiroHibler** [comment]
So, to clear it up, the bug occurs only if you DON'T set any styles to be loaded, correct?

**Comment by DanielRHarris** [comment]
That's correct.

**Comment by MiroHibler** [comment]
It should be fixed now :)

**Comment by DanielRHarris** [comment]
Works perfectly now, thanks!
